version: '3.8'

services:
  redis:
    image: redis
    container_name: app_redis
    network_mode: host
    expose:
      - 6379
  server:
    build:
      dockerfile: ../build/docker-server
      context: ./server/
    env_file:
      - ./build/docker.env
    container_name: app_server
    network_mode: host
    expose:
      - 3000
    depends_on:
      - redis
  client:
    build:
      dockerfile: ./build/docker-client
      context: ./
    container_name: app_client
    network_mode: host
    expose:
      - 4200
    depends_on:
      - server
