version: '3.8'

services:
  redis:
    image: redis
    container_name: app_redis
    network_mode: host
    expose:
      - 6379
  server:
    image: clojure:lein
    container_name: app_server
    command:
      # sh -c "lein uberjar && java -cp ./target/constructor.jar clojure.main -m app.server"
      sh -c "lein run"
    working_dir: /app/server
    network_mode: host
    expose:
      - 3000
    depends_on:
      - redis
    volumes:
      - ./server:/app/server:cached
      - /.m2
  client:
    build:
      dockerfile: ./build/docker-client
      context: ./
    container_name: app_client
    network_mode: host
    expose:
      - 4200
    depends_on:
      - server
